# Generated by Django 4.2.16 on 2024-11-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Weather', models.IntegerField(choices=[(1, 'Sunny'), (2, 'Rainy'), (3, 'Cloudy'), (4, 'Cold')])),
                ('State', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Google_Maps_Link', models.URLField(blank=True, max_length=500, null=True)),
                ('explore_img', models.ImageField(upload_to='explore/')),
                ('Description', models.CharField(max_length=5000)),
            ],
        ),
    ]
